name: 'deploy on gke'
author: 'Vishal Kumar Singh'

description: 'Deploy and test your simple html,css,js on gke'

branding:
  icon: 'clipboard'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'