apiVersion: v1
kind: Deployment
metadata:
  name: dash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: gcr.io/fluent-sprite-261715/dash